### PR TITLE
Fix `r` and `s` size to 32-bytes

### LINKED ISSUE #281: Incorrect assumption about signature length
Hello, I'm using this library in my project. 🙏🏻 

There is a bug to assume the length of signature's `r` and `s` as only `32` bytes. I have ever seen 31 bytes, 32 bytes, 33 bytes 🤔 When there is the negative `r` or `s`, 33 bytes, `asn1-parser/parseSignature` slices it until 32 bytes so it become polluted invalid signature.

If you assumed it with some documentation, could you share it?

### PR DESCRIPTION
**Pull request by moreal**
This pull request resolves #281.

The AWS KMS signs and responses with a signature formatted by ASN.1. And ASN.1 format serialize integer with `\x00` byte as prefix if it can be confused with negative integer. It serializes with only least bytes. So the integers, `r` and `s`, can be 33-bytes and 31-bytes.

The parameter `signature` of `secp256k1.ecdsaRecover` requires 64-bytes consists of 32-bytes `r` and 32-bytes `s`. So it is checking the condition.
https://github.com/odanado/aws-kms-provider/blob/ca5d7da4bfbf382cd2c14002d5efb0ba62b8ad25/src/crypto.ts#L33-L38
But the original code didn't care 31-bytes case. So I tried to fix the bug.

### CODE REVIEW

**Comment by moreal** [comment]
The E2E test seems failed by problem about credentials.. 😢  Could you check it? @odanado

**Comment by odanado** [comment]
The reason why the E2E test is failing is that the `secrets` isn't being passed to the workflow.

> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
> https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

File: src/asn1-parser.ts [hunk 1]
```diff
@@ -17,16 +34,40 @@ export function parsePublicKey(buf: Buffer) {
   return Buffer.from(value.valueBlock.valueHex.slice(1));
 }
 
-export function parseSignature(buf: Buffer) {
+/**
+ * Parse signature from the given signature.
+ * @param buf The buffer of the signature which following ASN.1 format.
+ * @returns The set consists of, `r` and `s`. The `r` and `s` are parsed from the given signature and converted to 32 statically sized format from ASN.1 format. For example, if there is 33-bytes unsigned integer  formatted by ASN.1, it will be converted into 32-length bytes which dropped the first byte. (e.g. `00e26f7c547cf497959af070ec7c43ebdbb3e4341395912d6ccc950b43e886781b` → `00e26f7c547cf497959af070ec7c43ebdbb3e4341395912d6ccc950b43e886781b`). And, if there is 31-bytes integer formatted by ASN.1, it will be padded into 32-length bytes with `0` byte. (e.g. `74e3e4d71e7385ae71042b0f99f7fbbf66e7760dd513ed2fcea754e2a9131c` → `0074e3e4d71e7385ae71042b0f99f7fbbf66e7760dd513ed2fcea754e2a9131c`).
```
Comment (odanado) [inline src/asn1-parser.ts:40]:
```suggestion
 * @returns The set consists of, `r` and `s`. The `r` and `s` are parsed from the given signature and converted to 32 statically sized format from ASN.1 format. For example, if there is 33-bytes unsigned integer  formatted by ASN.1, it will be converted into 32-length bytes which dropped the first byte. (e.g. `00e26f7c547cf497959af070ec7c43ebdbb3e4341395912d6ccc950b43e886781b` → `e26f7c547cf497959af070ec7c43ebdbb3e4341395912d6ccc950b43e886781b`). And, if there is 31-bytes integer formatted by ASN.1, it will be padded into 32-length bytes with `0` byte. (e.g. `74e3e4d71e7385ae71042b0f99f7fbbf66e7760dd513ed2fcea754e2a9131c` → `0074e3e4d71e7385ae71042b0f99f7fbbf66e7760dd513ed2fcea754e2a9131c`).
```

typo ?

File: src/asn1-parser.ts [hunk 2]
```diff
@@ -9,6 +9,23 @@ function toArrayBuffer(buffer: Buffer) {
...
+
+function pad(params: {
+  buffer: Buffer;
+  length: number;
+  element: number;
+}): Buffer {
+  const { buffer, length, element } = params;
+
+  const padding = Buffer.from(
+    [...Array(length - buffer.length)].map((x) => element)
```
Comment (odanado) [inline src/asn1-parser.ts:24]:
```suggestion
  const padding = Buffer.alloc(length - buffer.length, 0);
```

Could you use  `Buffer.alloc`?

File: src/asn1-parser.spec.ts [hunk 3]
```diff
@@ -28,22 +28,41 @@ describe("parsePublicKey", () => {
...
+
+    expect(signature.s.toString("hex")).toBe(
+      "e26f7c547cf497959af070ec7c43ebdbb3e4341395912d6ccc950b43e886781b"
+    );
+
     expect(signature.r.length).toBe(32);
     expect(signature.s.length).toBe(32);
+  });
+
+  it("ok with 140-length signature", () => {
```
Comment (odanado) [inline src/asn1-parser.spec.ts:50]: :memo:
https://runkit.com/odanado/61155266fdb6be001a2223e4

**Review by odanado — CHANGES_REQUESTED** [review]

File: src/asn1-parser.ts (hunk 1 above)
Comment (moreal) [reply src/asn1-parser.ts:40]: Yes, you're right 😉

File: src/asn1-parser.ts (hunk 2 above)
Comment (moreal) [reply src/asn1-parser.ts:24]: I hadn't know it, thanks! 🙏🏻

File: src/asn1-parser.spec.ts (hunk 3 above)
Comment (moreal) [reply src/asn1-parser.spec.ts:50]: I can't understand this comment what this means 😅 Coud you explain again?

Comment (odanado) [reply src/asn1-parser.spec.ts:50]: I'm sorry.

This is just a note for myself to help me understand the principle of the original problem (#281). This is not a review comment, so don't worry about it.

**Comment by odanado** [comment]
@moreal 
Could you merge the upstream master branch? E2E tests should then be running on GitHub Actions.

**Comment by moreal** [comment]
> 
> 
> @moreal
> Could you merge the upstream master branch? E2E tests should then be running on GitHub Actions.

I rebased this pull request on the `master` branch. Could you check it? 🙏🏻

**Comment by odanado** [comment]
:)

**Review by odanado — APPROVED** [review]
LGTM

**Comment by odanado** [comment]
Released: https://github.com/odanado/aws-kms-provider/releases/tag/v0.3.4
